name: docs
on:
  push:
    branches:
    - main

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.14

    - name: Install requirements
      run: |
        pip install sphinx==7.2.6 sphinx-rtd-theme==1.3.0 numpydoc==1.6.0 cachetools==5.3.2
        pip install chromatic_tda==1.0.8
        pip install numba==0.59.0
        sudo apt-get update
        sudo apt-get install libboost-all-dev
        pip install boost
        pip install -e .

    
    - name: Build docs
      run: |
        cd docs
        make html SPHINXOPTS='-W'
    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/